In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')
import seaborn as sns

# 1. Exploratory Data Analysis

In [2]:
train = pd.read_csv('train.csv', sep=',')
#test = pd.read_csv('test.csv',sep=',')

In [3]:
print("size of the data:",train.shape)


size of the data: (26941500, 25)


In [4]:
train.head(n=7)

Unnamed: 0            date_time  site_name  posa_continent  \
0    11576644  2013-01-30 09:48:21          2               3   
1    29520606  2014-11-23 22:37:12          2               3   
2    33049478  2014-12-28 16:25:08          2               3   
3    17432446  2014-05-28 09:23:46         34               3   
4    21390045  2014-07-07 18:15:12          2               3   
5    37315050  2014-07-10 12:22:02         17               1   
6    31994780  2013-11-28 08:50:57          2               3   

   user_location_country  user_location_region  user_location_city  \
0                     85                   235               43454   
1                     66                   442                  76   
2                     66                   442               35390   
3                    205                   354               51792   
4                     66                   311               31206   
5                    133                    19               18022   
6                     66                   174               47451   

   orig_destination_distance  user_id  is_mobile      ...        \
0                        NaN   112239          0      ...         
1                  4740.8784   586999          0      ...         
2                   647.8278   407093          0      ...         
3                        NaN   576076          0      ...         
4                   394.5247   849220          0      ...         
5                        NaN  1126166          0      ...         
6                        NaN  1033277          0      ...         

   srch_children_cnt  srch_rm_cnt srch_destination_id  \
0                  0            1                8263   
1                  0            1               12623   
2                  0            1                4476   
3                  0            1               14875   
4                  0            3                8291   
5                  0            1                8266   
6                  0            1               30793   

  srch_destination_type_id  is_booking  cnt  hotel_continent  hotel_country  \
0                        1           0    3                6             17   
1                        5           0    1                6            170   
2                        3           0    1                2             50   
3                        1           0    1                2            198   
4                        1           0    1                2             50   
5                        1           1    1                2             50   
6                        4           0    2                2             50   

   hotel_market  hotel_cluster  
0            23             82  
1           313             22  
2           842              7  
3           750             32  
4           191             91  
5           411             37  
6           666             73  

[7 rows x 25 columns]

In [5]:
# converting date_time to type (datetime) instead of string 
#train['date_time']=pd.to_datetime(train['date_time'],infer_datetime_format=True)
#train['srch_ci']=pd.to_datetime(train['srch_ci'],infer_datetime_format=True)
#train['srch_co']=pd.to_datetime(train['srch_co'],infer_datetime_format=True)

#train.dtypes

In [6]:
train.columns

Index(['Unnamed: 0', 'date_time', 'site_name', 'posa_continent',
       'user_location_country', 'user_location_region', 'user_location_city',
       'orig_destination_distance', 'user_id', 'is_mobile', 'is_package',
       'channel', 'srch_ci', 'srch_co', 'srch_adults_cnt', 'srch_children_cnt',
       'srch_rm_cnt', 'srch_destination_id', 'srch_destination_type_id',
       'is_booking', 'cnt', 'hotel_continent', 'hotel_country', 'hotel_market',
       'hotel_cluster'],
      dtype='object')

In [7]:
hotel_cluster = train['hotel_cluster'].unique()
np.sort(hotel_cluster)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
train['hotel_cluster'].describe()

count    2.694150e+07
mean     4.980311e+01
std      2.891860e+01
min      0.000000e+00
25%      2.500000e+01
50%      4.900000e+01
75%      7.300000e+01
max      9.900000e+01
Name: hotel_cluster, dtype: float64

In [9]:
for columns in train:
    print ('Column Name: ',columns)
    print (train[columns].unique())

Column Name:  Unnamed: 0
[11576644 29520606 33049478 ...,  5228215  7511623 37240708]
Column Name:  date_time
['2013-01-30 09:48:21' '2014-11-23 22:37:12' '2014-12-28 16:25:08' ...,
 '2013-09-28 14:12:09' '2014-07-19 23:09:32' '2014-03-02 10:01:07']
Column Name:  site_name
[ 2 34 17 37 11 24  8 33 13 22 26 53 18 30 23 28 29 27 25 35 15 10 45 14 32
  7 46  9 40 43 36  6 38 21 16 20 48 31 44 19 47 41  5  4  3]
Column Name:  posa_continent
[3 1 2 4 0]
Column Name:  user_location_country
[ 85  66 205 133 103  69   3  63 194  48  77 231 202  46   0 215 119  23
 235  19 196  27 117 158 115 195 154   1 149 123  30  68  80  52 167  12
  70  55  75 182 214 163  39 162  62 130 191 104  26 131  28   5  91 198
 179  32  57  71 218 181 190 230  58  83  82  22  24  50  29 229  60  59
 148  61 168  93  51  54 192  11 176  73 197   8  98 134 217  87 188 178
  76  95 180 151   4   6 141 206 144 174  45  47 101  72 108  65 223 239
  74 156  36 105 183 106 221  40 234 137 209 187 219  10 173 109  44 125


### Managing the Missing Data 

In [10]:
# Number of missing data 
train.isnull().sum(axis=0)

Unnamed: 0                         0
date_time                          0
site_name                          0
posa_continent                     0
user_location_country              0
user_location_region               0
user_location_city                 0
orig_destination_distance    9674092
user_id                            0
is_mobile                          0
is_package                         0
channel                            0
srch_ci                        33505
srch_co                        33505
srch_adults_cnt                    0
srch_children_cnt                  0
srch_rm_cnt                        0
srch_destination_id                0
srch_destination_type_id           0
is_booking                         0
cnt                                0
hotel_continent                    0
hotel_country                      0
hotel_market                       0
hotel_cluster                      0
dtype: int64

In [11]:
train_2 = train.dropna()
print ("size of the data without the missing data:", train_2.shape)

size of the data without the missing data: (17247893, 25)


### Converting Check In date, and Check Out date

In [12]:
train_2['ci_year']=train_2['srch_ci'].apply(lambda x: x[:4]).astype(int)
train_2['co_year']=train_2['srch_co'].apply(lambda x: x[:4]).astype(int)

/Users/soohyunlee/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/soohyunlee/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app


In [13]:
train2=train_2[train_2['ci_year']<2020]
train2['co_year'].unique()

array([2014, 2013, 2015, 2016, 2019])

In [14]:
train2['ci_year'].unique()

array([2014, 2013, 2015, 2016, 2018, 2012])

In [15]:
train2['srch_ci']=pd.to_datetime(train2['srch_ci'],infer_datetime_format=True)
train2['srch_co']=pd.to_datetime(train2['srch_co'],infer_datetime_format=True)

/Users/soohyunlee/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/soohyunlee/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app


In [16]:
train2['stay']= train2['srch_co']- train2['srch_ci']

/Users/soohyunlee/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [17]:
train2['stay']=train2['stay'].apply(lambda x: x.days)

/Users/soohyunlee/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [18]:
train3 = train2.drop(['date_time','srch_ci','srch_co'],axis=1)
train3.dtypes

Unnamed: 0                     int64
site_name                      int64
posa_continent                 int64
user_location_country          int64
user_location_region           int64
user_location_city             int64
orig_destination_distance    float64
user_id                        int64
is_mobile                      int64
is_package                     int64
channel                        int64
srch_adults_cnt                int64
srch_children_cnt              int64
srch_rm_cnt                    int64
srch_destination_id            int64
srch_destination_type_id       int64
is_booking                     int64
cnt                            int64
hotel_continent                int64
hotel_country                  int64
hotel_market                   int64
hotel_cluster                  int64
ci_year                        int64
co_year                        int64
stay                           int64
dtype: object

# 2. Splitting the data into Training data and Testing data 

In [19]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(train3, test_size=0.2)

In [20]:
train.shape

(13798312, 25)

# 3. Unsupervised K-Means Clustering

In [21]:
from sklearn.cluster import KMeans

In [22]:
mat = train.as_matrix()

In [23]:
kmeans = KMeans(n_clusters=5,random_state=0).fit(mat)
kmeans.labels_

array([3, 1, 0, ..., 3, 1, 4], dtype=int32)

In [24]:
kmeans.cluster_centers_

array([[  3.39182401e+07,   6.42099211e+00,   2.90591839e+00,
          8.88904484e+01,   3.10859891e+02,   2.81582591e+04,
          1.96117215e+03,   5.96825155e+05,   1.37352120e-01,
          2.46502908e-01,   6.02744433e+00,   2.03890330e+00,
          3.49409426e-01,   1.10269610e+00,   1.43812101e+04,
          2.63051748e+00,   8.18260218e-02,   1.47798025e+00,
          2.88784374e+00,   7.43405656e+01,   6.17912785e+02,
          4.98136913e+01,   2.01384433e+03,   2.01386630e+03,
          3.28505914e+00],
       [  3.80048700e+06,   6.26816418e+00,   2.89843397e+00,
          8.82706251e+01,   3.11537719e+02,   2.80037698e+04,
          1.96653695e+03,   5.87046794e+05,   1.35704896e-01,
          2.43588132e-01,   5.99751671e+00,   2.04257298e+00,
          3.49563776e-01,   1.10594466e+00,   1.43579421e+04,
          2.62633032e+00,   8.24479573e-02,   1.47568712e+00,
          2.89046640e+00,   7.39837680e+01,   6.20010627e+02,
          4.98461094e+01,   2.01384985e+03,